export const TRAINING_EXAMPLES = [
    { "text": "Give me your lunch money or else", "category": "bullying" },
    { "text": "everyone laughs at me in class", "category": "bullying" },
    { "text": "he keeps hitting me", "category": "physical_abuse" },
    { "text": "my dad burns me with cigarettes", "category": "physical_abuse" },
    { "text": "I feel so sad and lonely all the time", "category": "emotional_distress" },
    { "text": "nobody loves me", "category": "emotional_distress" },
    { "text": "I want to disappear forever", "category": "mental_health" },
    { "text": "I can't take this anymore, I want to die", "category": "mental_health" },
    { "text": "I have too much homework and I can't sleep", "category": "academic_pressure" },
    { "text": "my grades are dropping and my parents are mad", "category": "academic_pressure" },
    { "text": "someone has a knife in the bathroom", "category": "safety_threat" },
    { "text": "he said he will bring a gun to school", "category": "safety_threat" },
    { "text": "haha just kidding you idiot", "category": "prank" },
    { "text": "lol this is fake", "category": "prank" },
    { "text": "gabba gabba hey", "category": "prank" },
    { "text": "The teacher always singles me out", "category": "teacher_bullying" },
    { "text": "She humiliates me in front of the whole class", "category": "teacher_bullying" },
    { "text": "Marks are cut only for me", "category": "teacher_bullying" },
    { "text": "The teacher threatens my future", "category": "teacher_bullying" },
    { "text": "He shouts only at me and no one else", "category": "teacher_bullying" },
    { "text": "She calls me stupid in front of everyone", "category": "teacher_bullying" },
    { "text": "He makes me stand outside for no reason", "category": "teacher_bullying" },
    { "text": "The teacher scolded the whole class for being noisy", "category": "normal_discipline" },
    { "text": "My teacher is very strict about homework", "category": "normal_discipline" },
    { "text": "She is a fair but tough teacher", "category": "normal_discipline" },
    { "text": "I got a bad grade because I didn't study", "category": "normal_discipline" },
    { "text": "He told us to be quiet during the exam", "category": "normal_discipline" },

    { "text": "They keep calling me names every day", "category": "bullying" },
    { "text": "They push me around during lunch break", "category": "bullying" },
    { "text": "Everyone in class makes fun of my voice", "category": "bullying" },
    { "text": "They spread rumors about me online", "category": "bullying" },

    { "text": "They are posting bad things about me on Instagram", "category": "cyberbullying" },
    { "text": "Someone made a fake account to mock me", "category": "cyberbullying" },
    { "text": "People are sending me hate messages online", "category": "cyberbullying" },
    { "text": "They shared my photo without my permission", "category": "cyberbullying" },

    { "text": "He hits me when no one is watching", "category": "physical_abuse" },
    { "text": "My brother hurts me when he gets angry", "category": "physical_abuse" },
    { "text": "I get punished very badly at home", "category": "physical_abuse" },

    { "text": "I feel empty all the time", "category": "emotional_distress" },
    { "text": "I cry myself to sleep every night", "category": "emotional_distress" },
    { "text": "I feel like nobody understands me", "category": "emotional_distress" },
    { "text": "I feel invisible at school", "category": "emotional_distress" },

    { "text": "I don’t want to exist anymore", "category": "mental_health" },
    { "text": "I feel tired of living like this", "category": "mental_health" },
    { "text": "I feel hopeless about everything", "category": "mental_health" },
    { "text": "I feel like giving up", "category": "mental_health" },

    { "text": "My parents compare me to other students", "category": "academic_pressure" },
    { "text": "I feel scared before every exam", "category": "academic_pressure" },
    { "text": "Teachers expect too much from me", "category": "academic_pressure" },
    { "text": "I study all night but still fail", "category": "academic_pressure" },

    { "text": "My teacher always insults me in class", "category": "teacher_bullying" },
    { "text": "She never listens to my side of the story", "category": "teacher_bullying" },
    { "text": "He targets me for every mistake", "category": "teacher_bullying" },

    { "text": "Someone said they will hurt people at school", "category": "safety_threat" },
    { "text": "There is a fight planned after school", "category": "safety_threat" },
    { "text": "Someone brought something dangerous to school", "category": "safety_threat" },

    { "text": "The teacher warned us to behave properly", "category": "normal_discipline" },
    { "text": "We were punished for talking in class", "category": "normal_discipline" },
    { "text": "The teacher gave extra homework", "category": "normal_discipline" },

    { "text": "just joking bro", "category": "prank" },
    { "text": "this is all fake lol", "category": "prank" },
    { "text": "random words haha", "category": "prank" }
];
